FROM dunglas/frankenphp:php8.3-bookworm

RUN install-php-extensions mysqli
RUN docker-php-ext-install mysqli

WORKDIR /app

COPY . /app

EXPOSE 80

CMD ["frankenphp", "run", "--config", "/app/Caddyfile"]